name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install udev-dev
      run: sudo apt-get install libudev-dev
    - name: Build
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Run clippy
      run: cargo clippy --target x86_64-unknown-linux-gnu -- -D warnings
